Contributor/runtime, first version
decentraland/documentation pull request #105
Opened 2023-02-10 23:29 UTC by slezica

New (and hopefully correct and good) in this PR:

1. The entire **runtime** section in the sidebar.
2. The **identity** section with the **authentication chain** page.

It has one or two instances of `!!` and `[[` indicating TODOs and missing links, but it's mostly complete.

2023-02-14 18:41 UTC, menduz requested changes

2023-02-14 18:41 UTC, menduz commented on content/contributor/runtime/overview.md
> +- Make web3 payments
This may be too specific, it also allows executing calls to contracts, read state and sign messages

```suggestion
- Make web3 payments
```

2023-02-14 18:41 UTC, menduz commented on content/contributor/runtime/overview.md
> +Note that the SDK is _not_ part of the Decentraland protocol. Scenes can decide whether bundle it, or use alternative libraries that abstract some or all of the functionality.
```suggestion
Note that the SDK is _not_ part of the Decentraland protocol, the low level interfaces _are_ part of that protocol. Scenes can decide whether bundle it, or use alternative libraries that abstract some or all of the functionality.
```

2023-02-14 18:41 UTC, menduz commented on content/contributor/runtime/overview.md
> +Inside the sandboxed environment, [scenes]({{< relref "../content/entity-types/scenes" >}}) assume certain objects and functions are globally available. Some are standard ES-2020 objects (like `Date`
```suggestion
Inside the sandboxed environment, [scenes]({{< relref "../content/entity-types/scenes" >}}) assume certain objects and functions are globally available. Some are standard ES2020 objects (like `Date` or `Math`), and others are injected by the runtime to implement functionality such as requiring modules, logging messages and scheduling callbacks.
```

2023-02-14 18:41 UTC, menduz commented on content/contributor/runtime/overview.md
> +The [`require`]({{< relref "globals#module" >}}) global function can import modules provided by the [runtime library]({{< relref "execution" >}}). These modules allow selectively importing utilities
```suggestion
The [`require`]({{< relref "globals#module" >}}) global function can import modules provided by the [runtime library]({{< relref "execution" >}}). These modules allow selectively importing utilities such as the ECS or Communications systems.

It is important to notice at this stage, that even though it behaves similarly to Node.js, the `require` function doesn't load external modules from files. Instead, it provides proxy objects to interact with the "external" world, in this case, the Decentraland Explorer https://adr.decentraland.org/adr/ADR-102
```

2023-02-14 18:41 UTC, menduz commented on content/contributor/runtime/globals.md
> +1. [`console`](#console): a subset of the Node/browser `console` object.
```suggestion
1. [`console`](#console): a simple `console` object, implementing a subset of functions of the Browser/Node.js console.
```

2023-02-14 18:41 UTC, menduz commented on content/contributor/runtime/globals.md
> +2. [`module`](#module): a subset of Node's `module` object.
```suggestion
2. [`module`](#module): an object used to keep track of the `.exports` object.
```

2023-02-14 18:41 UTC, menduz commented on content/contributor/runtime/globals.md
> +3. [`exports`](#module): a shortcut to `module.exports`, as in Node.
```suggestion
3. [`exports`](#module): an object that the module may add its API to as it executes. Compatible with [CommonJS Modules 1.0](https://wiki.commonjs.org/wiki/Modules/1.0)
```

2023-02-14 18:41 UTC, menduz commented on content/contributor/runtime/globals.md
> +4. [`require`](#module): an implementation of Node's `require` for a curated list of modules.
```suggestion
4. [`require`](#module): a constrained implementation of the [CommonJS' Require](https://wiki.commonjs.org/wiki/Modules/1.0) function, used to load the external modules to interact with the engine, communications systems, the blockchain, etc.
```

2023-02-14 18:41 UTC, menduz commented on content/contributor/runtime/globals.md
> +5. [`setImmediate`](#scheduling): an implementation of Node's `setImmediate`.
```suggestion
5. [`setImmediate`](#scheduling): an implementation of Node's `setImmediate`. Schedules to run handler immediately after running tasks have been flushed from the JS's event loop.
```

2023-02-14 18:41 UTC, menduz commented on content/contributor/runtime/globals.md
> +Scenes can import and export objects using a Node-like interface.
```suggestion
Scenes can interact with other system components via using a CommonJS-like `require` or imports in a high level language like Typescript.
```

We can also discuss how `import {x} from `~system/Asd`` becomes `const {x} = require(~system/Asd)` thanks to Typescript and how it helps the devexp

2023-02-14 18:41 UTC, menduz commented on content/contributor/runtime/globals.md
> +require(moduleName: string): { exports: Object }
The exports is _the_ return type in this case
```suggestion
require(moduleName: string): ExportedObject
```

2023-02-14 18:41 UTC, menduz commented on content/contributor/runtime/globals.md
> +Scenes can (and must]]) export objects by setting keys in `module.exports`, or the `exports` shortcut.
Here also is a good place to mention high level import

2023-02-14 18:41 UTC, menduz commented on content/contributor/runtime/globals.md
> +When a scene needs to schedule callbacks with their execution controlled by the sandbox host, it can use the Node-like `setImmediate` global. These callbacks will queue up and be invoked at some impl
I'd avoid mentioning node or browsers as much as possible to prevent confusions. In the past I had argues with people not being able to execute node.js modules OOTB in scenes.

```suggestion
When a scene needs to schedule callbacks with their execution controlled by the sandbox host, it can use the `setImmediate` global. These callbacks will queue up and be invoked at some implementation-dependent point in the future, usually at the end of the [game loop tick](https://adr.decentraland.org/adr/ADR-148).
```

2023-02-14 18:41 UTC, menduz commented on content/contributor/runtime/execution.md
> +During the life-cycle of a scene, the runtime will ensure that calls to these methods are never made concurrently. The returned `Promise` will always be awaited before the scene receives a new call.
```suggestion
During the life-cycle of a scene, the runtime will ensure that calls to these methods are never made concurrently. The returned `Promise` will always be awaited before the scene receives a new call.
```

This promise will block the Renderer frame for this scene and vice-versa to produce back-pressure and prevent generating more frames than the renderer can process https://adr.decentraland.org/adr/ADR-148

This is so to prevent dropped frames, input lag and synchronization problems between scene and renderer

2023-02-14 18:41 UTC, menduz commented on content/contributor/runtime/execution.md
> +The life-cycle of a scene begins with the asynchronous `onStart` method. It's the place to make one-time initializations that must complete before the first call to [`onUpdate`](#onUpdate) is made.
```suggestion
The life-cycle of a scene begins with the asynchronous `onStart` method. It's the place to make one-time initializations that must complete before the first call to [`onUpdate`](#onUpdate) is made.

`onStart` is also the place to hydrate the initial state of the scene, e.g. loading generating or initial entities. During the execution of the `onStart`, the scene SHOULD also request the initial state to the renderer, to fetch the static entities components (link)
```

2023-02-14 18:41 UTC, menduz commented on content/contributor/runtime/execution.md
> +Exporting `onStart` is not required, and scenes are not expected to do anything in particular if they do. The method can be missing or do nothing and return an immediately resolved `Promise`.
```suggestion
Exporting `onStart` is recommended, but not required.
```

2023-02-14 18:41 UTC, menduz commented on content/contributor/runtime/components.md
> +###### `MeshRenderer` <small>[↗ source](https://github.com/decentraland/protocol/blob/ccb88d679f20c0e22840c324879d7b2535f6c9a6/proto/decentraland/sdk/components/mesh_renderer.proto#L7)</small> {#Mesh
We may want to make this links target=_blank

2023-02-14 18:41 UTC, menduz commented on content/contributor/runtime/components.md
> +Entities with a [`GltfContainer`](#GltfContainer) detect collisions according to meshes defined in the 3D model, and ignore this component.
I think both components are completely compatible, it would be strange to see though.
```suggestion

```

2023-02-14 18:41 UTC, menduz commented on content/contributor/runtime/components.md
> +Entities with a [`GltfContainer`](#GltfContainer) are rendered according to the referenced model, and ignore this component.
Same here

2023-02-14 18:41 UTC, menduz commented on content/contributor/runtime/components.md
> +Since the model has its own meshes and materials, this component overrides any behavior from [`MeshRenderer`](#MeshRenderer), [`MeshCollider`](#MeshCollider) and [`Material`](#Material).
Same
```suggestion
Since the model has its own meshes and materials, this component overrides any behavior from [`MeshRenderer`](#MeshRenderer), [`MeshCollider`](#MeshCollider) and [`Material`](#Material).
```

2023-02-14 18:41 UTC, menduz commented on content/contributor/runtime/components.md
> +Makes an Entity automatically reorient its `Transform` to face the camera. As the name indicates, it's used to display in-game billboards and frequently combined with [`TextShape`](#TextShape).
```suggestion
Makes an Entity automatically reorient its `Transform` ensuring that the entity is always facing towards the camera. As the name indicates, it's used to display in-game billboards and frequently combined with [`TextShape`](#TextShape).

Billboards can be applied to parent entities, and the children will be re-oriented respecting their local `Transform`. In other words, child entities can be re-oriented inside a Billboard e.g. to rotate it another extra 180 degrees.
```

2023-02-14 18:41 UTC, menduz commented on content/contributor/runtime/modules/engine_api.md
> +Timestamps aren't actually Unix-style timestamps. They are a type of shared incremental counter to sequence updates, with no relation to clock time. More on this [below](#timestamps).
Lamport timestamps are scoped using entityId+componentId as keys
```suggestion
Timestamps aren't actually Unix-style timestamps. They are a type of incremental counter to sequence updates, with no relation to clock time. More on this [below](#timestamps).
```

2023-02-14 18:41 UTC, menduz commented on content/contributor/runtime/modules/engine_api.md
> +## Supporting Legacy Scenes
I'd mention that the SDK6 and backwards is out of scope of the Dcl protocol

2023-02-14 18:41 UTC, menduz commented on content/contributor/runtime/modules/restricted_actions.md
> +###### `openNftDialog` {#openNftDialog}
missing # changeRealm

2023-02-14 18:44 UTC, slezica commented on content/contributor/runtime/overview.md
> +- Make web3 payments
How about "interact with the user's wallet", or something to that effect? Or do you think it's better to remove the line entirely?

2023-02-14 18:52 UTC, slezica commented on content/contributor/runtime/globals.md
> +Scenes can (and must]]) export objects by setting keys in `module.exports`, or the `exports` shortcut.
Does `export` from scene code work as expected?

2023-02-16 18:14 UTC, slezica commented on content/contributor/runtime/components.md
> +Makes an Entity automatically reorient its `Transform` to face the camera. As the name indicates, it's used to display in-game billboards and frequently combined with [`TextShape`](#TextShape).
Why this? Is it an alternative way to phrase it, or is this implying a technical detail I'm not aware of?

2023-02-16 18:21 UTC, slezica commented on content/contributor/runtime/components.md
> +###### `MeshRenderer` <small>[↗ source](https://github.com/decentraland/protocol/blob/ccb88d679f20c0e22840c324879d7b2535f6c9a6/proto/decentraland/sdk/components/mesh_renderer.proto#L7)</small> {#Mesh
Hmm, I would certainly open links in new tabs if I was browsing this page, but I think it's something we can leave to the user. Do you feel it makes an important difference?

2023-02-16 19:06 UTC, menduz commented on content/contributor/runtime/components.md
> +Makes an Entity automatically reorient its `Transform` to face the camera. As the name indicates, it's used to display in-game billboards and frequently combined with [`TextShape`](#TextShape).
In a second read, it is the same

2023-02-16 19:08 UTC, menduz commented on content/contributor/runtime/globals.md
> +{{< /info >}}
<3

2023-02-16 19:59 UTC, menduz commented on content/contributor/runtime/overview.md
> +- Make web3 payments
Decentraland enables an interface to access to the user's wallet and some evm related methods... I think saying "payments" is selling short the capabilities of what can actually be achieved, but probably it is good enough for most readers.

"Interact with ethereum" may be too vague

2023-02-16 20:03 UTC, menduz approved these changes
Awesome job!

2023-02-18 11:27 UTC, eordano approved these changes
Left just some minor suggestions! Amazing work!

2023-02-18 11:27 UTC, eordano commented on content/contributor/auth/authchain.md
> +1. Upload a new version of any entity they own (such as their profile).
[[entity]] maybe?

2023-02-18 11:27 UTC, eordano commented on content/contributor/auth/authchain.md
> +1. The `Ephemeral address` doesn't need to be an actual Ethereum account with funds in the blockchain. The field only represents a temporary public key.
```suggestion
1. The `Ephemeral address` doesn't need to be an actual Ethereum account with funds in the blockchain. The field might only represent a temporary public key.
```

2023-02-18 11:27 UTC, eordano commented on content/contributor/auth/authchain.md
> +There is no universal strategy to decide what the valid time window should be. The Foundation's World Explorer, for reference, requests authorization for its delegate key for one month.
```suggestion
There is no universal strategy to decide what the valid time window should be. The Foundation's World Explorer, for reference, requests authorization for its delegate key for one month.

Additionally, ephemeral keys should never hold funds, or the ability to move digital assets. Although technically possible, it's much safer for users if losing an ephemeral key never leads to financial losses. 
```

2023-02-18 11:27 UTC, eordano commented on content/contributor/runtime/modules/engine_api.md
> +This page explains the use of the CRDT to synchronize state between a locally running scene and the game engine, but the real potential of this mechanism lies in multiplayer scenarios. Using this pro
```suggestion
This page explains the use of the CRDT to synchronize state between a locally running scene and the game engine, but the real potential of this mechanism lies in multiplayer scenarios. Using this protocol, players can coordinate their game state and share the same experience.
```

2023-02-22 14:18 UTC, merged