doc: new entity type
decentraland/documentation pull request #17
Opened 2022-10-18 18:36 UTC by pedrotambo

2022-10-18 18:45 UTC, agusaldasoro approved these changes

2022-10-18 18:51 UTC, gonpombo8 requested changes

2022-10-18 18:51 UTC, gonpombo8 commented on content/contributor/tutorials/how-to-create-new-entity-type.md
> +slug: "/contributor/tutorials/how-to-create-an-entity"
```suggestion
url: "/contributor/tutorials/how-to-create-an-entity"
```

2022-10-18 18:54 UTC, gonpombo8 commented
![image](https://user-images.githubusercontent.com/16782417/196518836-480732c4-2242-4dc0-abb5-c7c8ec5cfcde.png)
also u can use the prop [sidebartitle](https://github.com/decentraland/documentation/blob/main/content/contributor/tutorials/how-to-run-a-catalyst.md?plain=1#L3) to avoid large titles 😄

2022-10-18 20:01 UTC, gonpombo8 approved these changes

2022-10-19 13:38 UTC, merged

2022-10-19 14:22 UTC, menduz commented on content/contributor/tutorials/how-to-create-new-entity-type.md
> +- What is the amount entities that will be created?
@pedrotambo please add the considerations here. I can ask myself those questions but there is no framework to decide on the answer