feat: add outfits
decentraland/documentation pull request #182
Opened 2023-05-30 19:10 UTC by pedrotambo

2023-05-31 13:57 UTC, hugoArregui approved these changes

2023-05-31 14:06 UTC, marianogoldman requested changes

2023-05-31 14:06 UTC, marianogoldman commented on content/contributor/content/entity-types/outfits.md
> +Outfits [pointers]({{< relref "../pointers" >}}) are the Ethereum address of the owner with a "`:outfits`" suffix . For example:
```suggestion
Outfits [pointers]({{< relref "../pointers" >}}) are the Ethereum address of the owner with a "`:outfits`" suffix. For example:
```

2023-05-31 14:06 UTC, marianogoldman commented on content/contributor/content/entity-types/outfits.md
> +Each outfit in `metadata.outfts[]` represents an outfit of the user, and has a number of properties:
```suggestion
Each outfit in `metadata.outfits[]` represents an outfit of the user, and has a number of properties:
```

2023-06-01 17:58 UTC, marianogoldman approved these changes

2023-06-01 19:51 UTC, merged