Rentals
decentraland/documentation pull request #41
Opened 2022-11-29 15:51 UTC by nicorajcodcl

New Rentals documentation

2022-11-29 15:52 UTC, nearnshaw approved these changes

2022-11-30 14:28 UTC, fzavalia requested changes

2022-11-30 14:28 UTC, fzavalia commented on content/player/marketplace/rentals.md
> +💡 Edit and cancel actions may require a transaction, which costs gas. See Transactions section below for more details.
```suggestion
💡 Edit and cancel require a transaction, which costs gas. See Transactions section below for more details.
```

2022-11-30 14:28 UTC, fzavalia commented on content/player/marketplace/rentals.md
> +You can check the Status of any rented LAND in My Store > My Assets. The possible status are:
```suggestion
You can check the Status of any rented LAND in My Assets > Store > On Rent. The possible status are:
```

2022-11-30 14:28 UTC, fzavalia commented on content/player/marketplace/rentals.md
> +If either the Price, Rent Period, or Expiration Date is changed, a transaction has to be sent by the LAND Owner in order to protect themselves from somebody hitting the Smart Contract directly (not f
```suggestion
If either the Price, Rent Period, or Expiration Date is changed, a transaction has to be sent by the LAND Owner in order to protect themselves from somebody using the previous listing signature on the Smart Contract directly (not from the Marketplace UI) and getting it from a lower price than desired or for an undesired duration. 
```

2022-12-01 14:25 UTC, nearnshaw approved these changes

2022-12-01 16:41 UTC, fzavalia approved these changes

2022-12-05 15:28 UTC, merged